### ISSUE TITLE
AutoClosingTag doesn't work in large files

### ISSUE THREAD

**Issue by KirillOsenkov** [mhutch/MonoDevelop.Xml#25]
In a large XML file, type `<a a="a"` and then type the closing `>`

The closing tag is likely not inserted. This is because at the time when the command handler runs the parse tree for the new snapshot that has the `>` that was just inserted is not yet available, so a call to GetSpineParser is recovered from the previous tree that doesn't have the closing `>`.

Since in the previous tree the `>` is not there, the element under caret is not `IsEnded` and the condition here bails:
https://github.com/mhutch/MonoDevelop.Xml/blob/f112aae3b9b64981555a28b2a5e00bbafda369a7/Editor/Commands/AutoClosingTagCommandHandler.cs#L66

It is noteworthy how even though the text and the parse tree is identical up to the caret position, the shape of the parse tree after the caret position is different and thus impacting whether the current element is ended or not. For small files the latest parse tree is usually available at that point, and in that tree the element is Ended, so the command handler executes.

This patch fixes it by always forcing the full tree for the latest snapshot:

![image](https://user-images.githubusercontent.com/679326/83316613-a49ec600-a1db-11ea-882d-ee10a212a6e1.png)

However this totally kills perf as it forces a synchronous parse of the latest snapshot immediately on typing. I'm not sure what's the best thing to do here, perhaps some heuristic to make just this particular case work.

**Comment by mhutch** [comment]
This should be fixed in #88. Sorry it took so long!
