### ISSUE TITLE
StackOverflow on large files with unclosed tags

### ISSUE THREAD

**Issue by KirillOsenkov** [mhutch/MonoDevelop.Xml#49]
Opening a large malformed file with thousands of unclosed tags crashes with StackOverflow as we use simple recursion and run out of stack

**Comment by mhutch** [comment]
Do you recall what method this was it? The parse itself doesn't use recursion and i'm unsure what else could have caused this.

**Comment by KirillOsenkov** [comment]
I have a repro file, assigning to myself to add the repro steps and the stack here on Monday.

**Comment by KirillOsenkov** [comment]
Couldn't assign, but I made a note not to forget.

**Comment by miloush** [comment]
Repro file: http://mirror.uwaterloo.ca/CTAN/web/fmweb/fmweb.mif

**Comment by miloush** [comment]
The method is `StructureTagger.GetNodesIntersectingRange`

**Comment by KirillOsenkov** [comment]
No repro on latest main. Must have been fixed.

Opens the file properly with 18044 errors :)

![image](https://github.com/mhutch/MonoDevelop.Xml/assets/679326/6d1b3fae-b08f-4554-878e-2e1f4dce6968)

**Comment by KirillOsenkov** [comment]
Also, sidenote, wow, what a diabolical file format.

**Comment by miloush** [comment]
This is Maker Interchange Format used by Adobe FrameMaker, I believe it predates XML.

https://help.adobe.com/en_US/framemaker/mifreference/mifref.pdf

**Comment by mhutch** [comment]
Interesting, thanks for sharing!

MonoDevelop.Xml could probably support it fairly easily via the currently-unused extensible parser state machine that was originally used for supporting HTML and ASPX, if anyone ever wanted to write a MIF language service 🤣
