### ISSUE TITLE
XmlCompletionSource doesn't work in projection buffers

### ISSUE THREAD

**Issue by KirillOsenkov** [mhutch/MonoDevelop.Xml#59]
In projection buffer scenarios (e.g. when you're viewing a diff of changes in an .xml file), the completion source throws as soon as you make an edit, because the XmlBackgroundParser expects to be created on content type 'xmlcore', but it gets 'projection'.

I think that instead of this:
https://github.com/mhutch/MonoDevelop.Xml/blob/8ec9b9a143175ca5d20b07a63b8b9289275d90fa/Editor/Completion/XmlCompletionSource.cs#L33

we should be retrieving the XmlBackgroundParser on demand from whichever buffer we're given by the completion infrastructure, and carry the parser provider in a field, instead of the parser for the top buffer.

**Comment by KirillOsenkov** [comment]
Proposed fixes:

Update to latest MonoDevelop.Xml:
https://github.com/mhutch/MonoDevelop.MSBuildEditor/pull/72

Use XmlParserProvider in MonoDevelop.Xml:
https://github.com/mhutch/MonoDevelop.Xml/pull/60

Update MonoDevelop.MSBuildEditor:
https://github.com/KirillOsenkov/MonoDevelop.MSBuildEditor/pull/1

**Comment by mhutch** [comment]
Fixes merged, is this resolved now?

**Comment by KirillOsenkov** [comment]
Just this last part is missing:
https://github.com/mhutch/MonoDevelop.MSBuildEditor/pull/77

**Comment by KirillOsenkov** [comment]
Updated that PR to latest now.
