### ISSUE TITLE
AutoClosingTag missing self-closed tags

### ISSUE THREAD

**Issue by miloush** [mhutch/MonoDevelop.Xml#83]
```xml
<r>
 <a e="v" /|
</r>
```

Type `>`.
Expected: nothing extra inserted.
Actual: `<a e="v" />|</a>`.

Note that the outer element, the attribute and the new line before `</r>` are critical for repro.

@KirillOsenkov

**Comment by KirillOsenkov** [comment]
@mhutch FYI we're periodically running into this

**Comment by mhutch** [comment]
Ah, thanks for the repro! I never saw this myself as I always had the closing `>` auto-inserted so the document would never have the incomplete nodes that caused this to happen. It should be fixed in #88.

**Comment by KirillOsenkov** [comment]
Can confirm this is now fixed, thanks!
